name: "Terraform Workflow"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  checkformatting:
    name: Check the Terraform Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7

      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Check Terraform Configuration files formatting
        run: |
          cd dev
          terraform fmt -check=true
          if [ $? -ne 0 ]; then
            echo "ERROR: Terraform configuration files are not formatted correctly"
            exit 1
          fi
          echo "SUCCESS: Terraform configuration files are formatted correctly"
          exit 0
        continue-on-error: true

      - name: Next Step After Verification
        run: echo "Successfull Steps"

  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'gcp'
        only_warn: true
        sarif_upload: true
        #non_recursive:
        #iac_dir:
        #policy_path:
        #skip_rules:
        #config_path:
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif

  driftctl:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_DEFAULT_CREDENTIALS }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      CLOUDSDK_CORE_PROJECT: "student100"
    steps:

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_DEFAULT_CREDENTIALS }}

      - name: Run driftctl
        uses: snyk/driftctl-action@v1.2.0
        env:
          DCTL_TO: gcp+tf
          DCTL_FROM: tfstate+gs://cicdstatebackup/dev/default.tfstate
          DCTL_ONLY_MANAGED: true
        continue-on-error: true

  plan:
    needs: [checkformatting, driftctl, terrascan_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan

  devdeployment:
    name: Deploy to Dev Environment
    needs: [plan]
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_DEFAULT_CREDENTIALS }}

    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7

      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          cd dev
          terraform init

      - name: Terraform Validate
        run: |
          cd dev
          terraform validate

      - name: Terraform Plan
        run: |
          cd dev
          terraform plan -no-color > tfplan.txt
          terraform plan -out=tfplan

      - name: Upload the Artifact
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: |
            dev/tfplan.txt
            dev/tfplan

      - name: Terraform Auto Apply
        run: |
          cd dev
          terraform apply -auto-approve

      

